CREATE TABLE IF NOT EXISTS reading (
  id          INTEGER                  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  sensor_id   UUID                     NOT NULL,
  date_time   TIMESTAMP WITH TIME ZONE NOT NULL,
  temperature NUMERIC (4, 1)           NOT NULL,
  humidity    NUMERIC (4, 1)           NOT NULL,
  pressure    NUMERIC (5, 1)           NOT NULL
);
