-- id name description mac ip key
CREATE TABLE IF NOT EXISTS sensor_type (
    id          INTEGER                  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    type_name   VARCHAR (30)             NOT NULL
);
CREATE TABLE IF NOT EXISTS sensor (
    id          INTEGER                  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    sensor_id   UUID                     NOT NULL,
    sensor_type INTEGER                  NOT NULL,
    sensor_name VARCHAR (30)             NOT NULL,
    description VARCHAR (120)            NOT NULL,
    mac         VARCHAR (17)                 NULL,
    host        VARCHAR (60)                 NULL,
    added_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE TABLE IF NOT EXISTS device_type (
    id          INTEGER                  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    type_name   VARCHAR (30)             NOT NULL
);
CREATE TABLE IF NOT EXISTS device (
    id          INTEGER                  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    device_id   UUID                     NOT NULL,
    device_type INTEGER                  NOT NULL,
    device_name VARCHAR (30)             NOT NULL,
    description VARCHAR (120)            NOT NULL,
    mac         VARCHAR (17)                 NULL,
    host        VARCHAR (60)                 NULL,
    added_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE TABLE IF NOT EXISTS reading (
    id          INTEGER                  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    sensor_id   UUID                     NOT NULL,
    date_time   TIMESTAMP WITH TIME ZONE NOT NULL,
    temperature NUMERIC (4, 1)           NOT NULL,
    humidity    NUMERIC (4, 1)           NOT NULL,
    pressure    NUMERIC (5, 1)           NOT NULL
);
